name: Publish Extension
on:
  pull_request:
    types: [closed]
  workflow_dispatch:

env:
  GIT_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || 'main' }}

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    if: >
        ( github.event_name == 'pull_request' &&
        github.event.pull_request.base.ref == 'main' &&
        contains(github.event.pull_request.title, 'Changeset version bump') ) ||
        github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Install Dependencies
        run: |
          npm install -g vsce ovsx
          npm install
          cd webview-ui
          npm install
          cd ..
      - name: Build VSIX
        run: npm run vsix
      - name: Create Tag
        run: |
          VERSION=$(jq -r '.version' package.json)
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
      - name: Create Release
        run: |
          VERSION=$(jq -r '.version' package.json)
          gh release create "v$VERSION" --title "Release v$VERSION" --notes "Automated release of version $VERSION"
      - name: Upload VSIX to Release
        run: |
          VERSION=$(jq -r '.version' package.json)
          gh release upload "v$VERSION" "bin/roo-code-$VERSION.vsix"
